networks:
  hyperion_net:
    driver: bridge

volumes:
  postgres_data:
  # Definimos volumen para que la DB persista aunque el contenedor muera

services:
  # --- CAPA DE DATOS Y CACHÉ ---
  redis:
    image: redis:alpine
    container_name: hyperion_cache
    restart: always
    networks:
      - hyperion_net
    ports:
      - "6379:6379"

  postgres_db:
    image: postgres:15-alpine
    container_name: hyperion_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-hyperion_secret}
      - POSTGRES_DB=${DB_NAME:-hyperion_audit}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyperion_net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: hyperion_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@hyperion.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin_pass}
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    networks:
      - hyperion_net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hyperion_backend
    restart: always
    ports:
      - "7860:7860"
    # 🔥 Forzamos el punto de entrada ignorando por completo el CMD del Dockerfile anterior
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
    depends_on:
      - redis
      - postgres_db
    networks:
      - hyperion_net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hyperion_dashboard
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend # 👈 Cambiado: arranca justo después del backend sin esperar validación estricta
    networks:
      - hyperion_net