name: Hyperion Keep Alive

on:
  schedule:
    # Esto ejecuta el bot cada 6 horas (puedes ajustarlo)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite activar el bot manualmente desde GitHub

jobs:
  ping_panels:
    runs-on: ubuntu-latest
    steps:
      - name: Despertar Panel Principal
        run: curl -sL "https://hyperion-soc.streamlit.app/" > /dev/null

      - name: Despertar Panel de Auditoria
        run: curl -sL "https://hyperion-audit.streamlit.app/" > /dev/null